# Generated by Django 5.2 on 2025-04-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
