# Generated by Django 5.2 on 2025-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmg', '0005_enquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['position', '-last_modified_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['position', '-last_modified_at']},
        ),
        migrations.AddField(
            model_name='faq',
            name='position',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='service',
            name='position',
            field=models.IntegerField(default=10),
        ),
    ]
