# Generated by Django 5.2 on 2025-04-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmg', '0008_display_displayimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayimage',
            old_name='property',
            new_name='display',
        ),
        migrations.AlterField(
            model_name='displayimage',
            name='image',
            field=models.ImageField(upload_to='display_images_new/'),
        ),
    ]
