# Generated by Django 5.2 on 2025-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmg', '0009_rename_property_displayimage_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
