# Generated by Django 5.2 on 2025-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmg', '0012_remove_property_category_remove_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
